CREATE TABLE "GROUPS_COUNT_BY_CITIES" AS
SELECT CT.CITY_ID, CT.CITY, (SELECT COUNT(GR.CITY_ID) FROM "GROUPS" AS GR WHERE CT.CITY_ID = GR.CITY_ID) AS GROUPS_COUNT_BY_CITY 
FROM "CITIES" AS CT 
GROUP BY CT.CITY_ID, CT.CITY
