CREATE TABLE "GENERAL_INFORMATION_OF_NOT_HORROR_EVENTS_OPENED" AS
SELECT EV.EVENT_ID, 
CASE LEN(EV.DESCRIPTION) > 500
    WHEN TRUE THEN SUBSTR(EV.DESCRIPTION, 0, 500) || '...'
    WHEN FALSE THEN EV.DESCRIPTION || '...'
END AS GENERAL_DESCRIPTION,
EV.DURATION, 
CONCAT(EV.EVENT_URL, EV.DURATION, EV.EVENT_ID) AS LINK_PROCESSED,
GR.GROUP_ID, 
GR.DESCRIPTION,
CA.CATEGORY_NAME FROM "EVENTS" EV
LEFT JOIN "GROUPS" AS GR ON GR.GROUP_ID = EV.GROUP_ID
LEFT JOIN "CATEGORIES" AS CA ON CA.CATEGORY_ID = GR.CATEGORY_ID
WHERE GR.JOIN_MODE = 'open' AND GR.RATING >= 4.8 AND CA.CATEGORY_ID <> 24